// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHtCgQ4mBfRv9X9sMvIR76M3DDgwuvV6w',
    appId: '1:553953274955:web:a8c303aa02dd266190f1ce',
    messagingSenderId: '553953274955',
    projectId: 'tascd-app',
    authDomain: 'tascd-app.firebaseapp.com',
    storageBucket: 'tascd-app.appspot.com',
    measurementId: 'G-YLDBVED7S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1upXmBfa_u73Owc80sHQ53zAfSeoBtz8',
    appId: '1:553953274955:android:f4711b4844e1ad7290f1ce',
    messagingSenderId: '553953274955',
    projectId: 'tascd-app',
    storageBucket: 'tascd-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfvsMt2U0SYDUMTtYmBobP8FX51cUWe8s',
    appId: '1:553953274955:ios:4bef99ca81758b4690f1ce',
    messagingSenderId: '553953274955',
    projectId: 'tascd-app',
    storageBucket: 'tascd-app.appspot.com',
    iosClientId: '553953274955-mui982c67epap4nsiq9fn3vu8gr7u09f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tascd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfvsMt2U0SYDUMTtYmBobP8FX51cUWe8s',
    appId: '1:553953274955:ios:342ae74f06b1948890f1ce',
    messagingSenderId: '553953274955',
    projectId: 'tascd-app',
    storageBucket: 'tascd-app.appspot.com',
    iosClientId: '553953274955-qhkdb0efj6g27hcbk4p0dpo019lt9940.apps.googleusercontent.com',
    iosBundleId: 'com.example.tascd.RunnerTests',
  );
}
